### PR TITLE
fix classnames overwrites in Tab, TagInput, FilePicker, TextDropdown

### LINKED ISSUE #946: Tab's className has been replaced
When I try to
```
<Tab className="hello">
```
I will lose the theme classes defined by the lib, do you think it makes sense to add the capability to allow the user to extend their own classes?

https://github.com/segmentio/evergreen/blob/master/src/tabs/src/Tab.js#L90

### PR DESCRIPTION
**Pull request by tusharf5**
## Overview

fixes #946 

Adds `className` prop to some components using the `classnames` library .

The only place where it is missing now is `MenuItem.js`. I did not add it there as another PR is modifying that file which would result in merge conflicts.

## Screenshots (if applicable)

Not applicable.

## Testing

Tested locally. Does not break any existing component styles.

### CODE REVIEW

File: src/file-picker/src/FilePicker.js [hunk 1]
```diff
@@ -182,7 +186,12 @@ FilePicker.propTypes = {
   /**
    * Placeholder of the text input
    */
-  placeholder: PropTypes.string
+  placeholder: PropTypes.string,
+
+  /**
+   * Class name passed to the FilePicker.
```
Comment (colinlohner) [inline src/file-picker/src/FilePicker.js:192]: Can you add "Only use this if you know what you are doing." to these comments

Comment (colinlohner) [reply src/file-picker/src/FilePicker.js:192]: @tusharf5 sorry just noticed, that we want to add this

Comment (tusharf5) [reply src/file-picker/src/FilePicker.js:192]: Sure, I'll add it just now.
