### PR TITLE
fixes #450

### LINKED ISSUE #450: Combobox does not scroll to selected item
Steps to reproduce:

1. Select an item from combobox.
2. Open combobox by click toggle button.

See the attachment! Do you need a PR?

bug

### PR DESCRIPTION
**Pull request by jongsue**
fixes #450
highlightedIndex from downshift seems to make this bug.
I've changed to get highlightedIndex from our props.

combobox-scroll

### CODE REVIEW

File: src/autocomplete/src/Autocomplete.js [hunk 1]
```diff
@@ -237,7 +238,9 @@ export default class Autocomplete extends PureComponent {
                   },
                   inputValue,
                   selectedItem,
-                  highlightedIndex,
+                  highlightedIndex: this.props.items.includes(selectedItem)
+                    ? this.props.items.indexOf(selectedItem)
+                    : 0,
                   selectItemAtIndex,
                   ...restDownshiftProps
```
Comment (mshwery) [inline src/autocomplete/src/Autocomplete.js]: By removing it from the destructure at the top it is being passed in `...restDownshiftProps`. Your code change for `children` here will be ignored because it is being overwritten by the value later.

Comment (jongsue) [reply src/autocomplete/src/Autocomplete.js]: Oops, you're right! 
I'll add highlightedIndex to the destructure
